### ISSUE TITLE
 Feature/Bug Solution To Stepping Speed Related Issue (kernel only tracing)

### ISSUE THREAD

**Issue by m853ax** [HyperDbg/HyperDbg#39] opened 2021-06-16 20:07 UTC
I just took a look at the stepping process and might found an alternative from spamming the step packet.
My idea would be to do a system similar to the ept hook one where messages can be stored in a buffer and be sent afterwards.(This might fix the vmware issue related to speed and unexpected slow down). Brainstormed an alternative aswell that would add a new feature to the debugger also know as tracing that would be able to record instructions a way faster keeping them in a buffer and finally saving in a file. I think this should be a priority for this project as his main goal is debugging and tracing is an important part of it. So whenever possible implement those features, i might start looking for it personally aswell. Forgot to mention: all data saved must not cross the um cli application(causing big slowdowns), but must be directly written from km to file in guest's machine (similar to x64dbg tracing).

**Comment by m853ax** [comment] 2021-06-16 20:53
without mentioning the ShowAllRegisters() func that sends a separate packet slowing down further

**Comment by m853ax** [comment] 2021-06-16 20:54
hope this feature can be added. for the rest, this debugger is near to perfection :)

**Comment by SinaKarvandi** [comment] 2021-06-17 07:08
Thank you for reporting a solution.
The idea about recording and saving traces into files is perfect and will be added in the next versions, so thanks for suggesting it.

But about the first solution, I didn't get the point. Do you mean to create a shared buffer between VMware and HyperDbg host and transfer data in this buffer?

**Comment by m853ax** [comment] 2021-06-17 11:19
my idea was to accumulate data before sending it, like in immediate_messaging = off

**Comment by m853ax** [comment] 2021-06-17 11:21
not sure if that work though

**Comment by m853ax** [comment] 2021-07-02 23:04
lol i might found out the speed problem. i just turned off net and it just worked

**Comment by m853ax** [comment] 2021-07-02 23:04
not sure how it can be connected to the issue though

**Comment by m853ax** [comment] 2021-07-02 23:05
hope you can find the problem :)

**Comment by m853ax** [comment] 2021-07-02 23:05
> lol i might found out the speed problem. i just turned off net and it just worked

not even 1 stop, working flawlessly.

**Comment by SinaKarvandi** [comment] 2021-07-03 15:37
You mean you disconnect from the internet and everything started to work normally?

**Comment by m853ax** [comment] 2021-07-03 18:38
exact

**Comment by SinaKarvandi** [comment] 2021-07-04 07:54
okay, thank you
I'll check it.

**Comment by m853ax** [comment] 2021-07-14 16:50
my log just stopped with `err checksum is invalid`

**Comment by m853ax** [comment] 2021-07-14 16:51
anything that could affect that?

**Comment by SinaKarvandi** [comment] 2021-07-14 19:42
The checksum is a way to check the data integrity of packets over a serial connection, and it's implemented exactly like gdb-protocol. If you're using a physical serial cable, then it's pretty okay. Serial cables are not 100% true about the data and might lose some of the data during data transfer, but it's weird if you're using VMWare virtual serial device. Because it's a software-level emulation of serial, and there is no error in transferring data. So, If you're using a virtual serial device, then can you regenerate the error? I mean, under what condition do you see this error?

**Comment by m853ax** [comment] 2021-07-14 19:50
im using `i` command this time and stepping goes through km & um

**Comment by SinaKarvandi** [comment] 2021-07-16 12:03
It's just a normal command with a normal serial connection (just like others commands). I mean under what condition do you see this error?

**Comment by m853ax** [comment] 2021-07-16 12:57
this happened only as said when moving between km & um

**Comment by m853ax** [comment] 2021-07-16 12:57
this is the only difference between other tests

**Comment by SinaKarvandi** [comment] 2021-07-16 13:18
Does it happen everytime you switch from kernel to user? and is it um -> km or km->um or both of them?

**Comment by m853ax** [comment] 2021-07-16 15:46
both

**Comment by m853ax** [comment] 2021-07-16 15:46
it goes both directions

**Comment by SinaKarvandi** [comment] 2021-08-13 22:18
![Capture](https://user-images.githubusercontent.com/13383992/129423371-722a53a7-e763-4a37-9d66-b2917334d98d.PNG)
Hey,
I re-test everything, and the 'i' command seems to be fine for me. I can't reproduce the error.
Do you still have a problem with it?

**Comment by SinaKarvandi** [comment] 2021-08-19 08:21
Please re-open the issue if you still have a problem with it.

**Comment by SinaKarvandi** [comment] 2021-08-19 20:37
H

**Comment by SinaKarvandi** [comment] 2021-08-19 20:38
Hello,
Would you please re-test HyperDbg's latest commit to see if you still have issues with speed or not? I think the issue is now, solved for 'p' and 't' commands, but not 'i'.

**Comment by m853ax** [comment] 2021-08-19 20:45
im currently not testing with hyperdbg

**Comment by m853ax** [comment] 2021-08-19 20:45
gonna let you know in case i encounter any problem again

**Comment by SinaKarvandi** [comment] 2021-08-19 21:15
That's okay.
In my tests the problem with 't' and 'p' is fixed, however, 'i' still has problem.

**Closed** 2023-06-02 05:14 UTC
Labels: bug, help wanted
