### ISSUE TITLE
build error | 'UsifHardwareDriver': undeclared identifier

### ISSUE THREAD

**Issue by expend20** [HyperDbg/HyperDbg#176] opened 2022-06-02 08:23 UTC
**Describe the bug**

I see the error:

```
HyperDbg\hyperdbg\kdserial\hardware.c(43,24): error C2065: 'UsifHardwareDriver': undeclared identifier
```

While building with `10.0.22621.0` WDK. Presumably it should in `c:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km\uart.h`, somewhere here:

```c++
...
#if defined(_X86_) || defined(_AMD64_)

extern UART_HARDWARE_DRIVER Legacy16550HardwareDriver;
extern UART_HARDWARE_DRIVER Uart16550HardwareDriver;
extern UART_HARDWARE_DRIVER SpiMax311HardwareDriver;
extern UART_HARDWARE_DRIVER MM16550HardwareDriver;
extern UART_HARDWARE_DRIVER IaLpssHardwareDriver;

#elif defined(_ARM_) || defined(_ARM64_)
...
```

But it's not.

Just commenting that line unbreaks the build.

**Comment by expend20** [comment] 2022-06-03 08:04
hi @SinaKarvandi,
Thanks for the reply, so I guess it should be exposed through a header like `usif.h`?

**Comment by SinaKarvandi** [comment] 2022-06-03 08:57
Yep, but it's weird because when you clone HyperDbg, it should be available by default on your project. It's in one of the files of the project.

**Comment by SinaKarvandi** [comment] 2022-06-03 12:16
Hey, 
@BehroozAbbassi encountered the same error and he solved it by changing the target SDK.
You probably installed two or more SDK versions. 

![image](https://user-images.githubusercontent.com/13383992/171851599-09891a27-e96a-4bce-b044-ebde6ae3b72f.png)

**Comment by SinaKarvandi** [comment] 2022-06-03 15:21
Also, please notify us if the problem is solved (or close the issue if it's fixed).

**Closed** 2022-06-13 10:53 UTC
Labels: build error
