### ISSUE TITLE
vs2019 community build error

### ISSUE THREAD

**Issue by botao1995** [HyperDbg/HyperDbg#34] opened 2021-05-30 07:56 UTC
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 __stdio_common_vsprintf，函数 _vsnprintf_l 中引用了该符号	hprdbghv	D:\code\HyperDbg\hyperdbg\hprdbghv\Debugger.obj	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 __stdio_common_vsprintf_s，函数 _vsprintf_s_l 中引用了该符号	hprdbghv	D:\code\HyperDbg\hyperdbg\hprdbghv\Logging.obj	1

**Comment by SinaKarvandi** [comment] 2021-05-30 08:15
Would you please edit your issue in English? I'm not Chinese :(
Thanks

**Comment by botao1995** [comment] 2021-05-30 08:26
> Would you please edit your issue in English? I'm not Chinese :(
> Thanks
sorry，The mistakes I encountered are as follows

Error LNK2019 unresolved external symbol__ stdio_ common_ Vsprintf, function_ vsnprintf_ L, the symbol hprdbghv D is referenced in the file: D:\code\HyperDbg\hyperdbg\hprdbghv\Debugger.obj 1

Error LNK2019 unresolved external symbol__ stdio_ common_ vsprintf_ s. Function_ vsprintf_ s_ L refers to the symbol hprdbghv D:\code\HyperDbg\hyperdbg\hprdbghv\Logging.obj 1

**Comment by SinaKarvandi** [comment] 2021-05-30 08:40
Weird,
Did you use: `git clone --recursive https://github.com/HyperDbg/HyperDbg.git`
I mean did you use --recursive?
Seems that there is a problem with the Chinese version of visual studio because we see another problem (somehow the same) in 
https://github.com/HyperDbg/HyperDbg/issues/26

**Comment by botao1995** [comment] 2021-05-30 08:53
> Weird

yes, i used   --recursive
I think it's not the language version of visual studio 2019. It's more likely to be WDK or SDK
https://community.osr.com/discussion/292312/linker-error-unresolved-external-symbol-stdio-common-vsprintf-with-rtlstringcbvprintfa

**Comment by botao1995** [comment] 2021-05-30 09:22
> Weird,
> Did you use: `git clone --recursive https://github.com/HyperDbg/HyperDbg.git`
> I mean did you use --recursive?
> Seems that there is a problem with the Chinese version of visual studio because we see another problem (somehow the same) in
> #26
I also use the English version of the prompt error.
![image](https://user-images.githubusercontent.com/47848566/120098964-6aa82d00-c16b-11eb-8e20-692f0a8fbd5a.png)

**Comment by SinaKarvandi** [comment] 2021-05-30 10:06
Yep, seemed to be a WDK or SDK problem. Maybe I used the wrong header. Or your WDK or SDK is outdated. I cannot reproduce the error to investigate the problem. Please keep us updated if you solved the issue.

**Comment by botao1995** [comment] 2021-05-30 15:19
> Yep, seemed to be a WDK or SDK problem. Maybe I used the wrong header. Or your WDK or SDK is outdated. I cannot reproduce the error to investigate the problem. Please keep us updated if you solved the issue.

I have solved this problem. It needs to add ucrtd.lib to the link library. If this project can support all Windows systems, it will be more perfect

**Comment by SinaKarvandi** [comment] 2021-05-30 16:19
Cool! Would you please send us a pull request and solve the problem or tell us what exactly should be done to solve it?

**Comment by botao1995** [comment] 2021-05-31 01:24
> Cool! Would you please send us a pull request and solve the problem or tell us what exactly should be done to solve it?

See also #35

**Comment by SinaKarvandi** [comment] 2021-05-31 04:00
Merged.
Thank you

**Closed by SinaKarvandi** 2021-05-31 04:00 UTC

**Comment by botao1995** [comment] 2021-05-31 05:01
> Merged.
> Thank you

You are welcome to China
