### ISSUE TITLE
Unresponsive hyperdbg-cli.exe after `load vmm` since 4f0d0dc3bf3686772a58ebe85221dc3374be8188

### ISSUE THREAD

**Issue by sjzbwdiy** [HyperDbg/HyperDbg#323] opened 2023-11-25 13:09 UTC
**Describe the bug**
Regression

**To Reproduce**
test 0:

0. `git checkout fac10fd8309bd40a43c6caa3eac2f33e4e2a1e65`
1. `hyperdbg-cli.exe`
2. `.connect local`
3. `load vmm`
4. problem: unresponsive hyperdbg-cli.exe

test 1:

0. `git checkout 4f0d0dc3bf3686772a58ebe85221dc3374be8188`
1. `hyperdbg-cli.exe`
2. `.connect local`
3. `load vmm`
4. problem: unresponsive hyperdbg-cli.exe

test 2:

0. `git checkout 3f1b1a7489480b6f3a434f34d5f1d9b33f06e12c`
1. `hyperdbg-cli.exe`
2. `.connect local`
3. `load vmm`
4. problem: unresponsive VM

test 3:

0. `git checkout 4f0d0dc3bf3686772a58ebe85221dc3374be8188~1`
1. `hyperdbg-cli.exe`
2. `.connect local`
3. `load vmm`
4. no problem

**Expected behavior**
No regression

**Screenshots**
fac10fd8309bd40a43c6caa3eac2f33e4e2a1e65]:
![fac10fd8309bd40a43c6caa3eac2f33e4e2a1e65](https://github.com/HyperDbg/HyperDbg/assets/152008115/40b5fcc6-33ca-4173-86d0-a2dfca7a4fd9)
4f0d0dc3bf3686772a58ebe85221dc3374be8188:
![4f0d0dc3bf3686772a58ebe85221dc3374be8188](https://github.com/HyperDbg/HyperDbg/assets/152008115/b2c91dc5-920e-4067-9cf1-fc09298dec18)
3f1b1a7489480b6f3a434f34d5f1d9b33f06e12c:
![3f1b1a7489480b6f3a434f34d5f1d9b33f06e12c](https://github.com/HyperDbg/HyperDbg/assets/152008115/17da6b04-8107-449d-abd0-86b362cddcc4)
94dba4945533a9ad2feb78da5734636ebcacecf6 (`4f0d0dc3~1`):
![94dba4945533a9ad2feb78da5734636ebcacecf6](https://github.com/HyperDbg/HyperDbg/assets/152008115/97be33c6-7857-483d-9b75-2ef18acd81ed)

**Desktop (please complete the following information):**
 - OS: Win 10 1909
 - Processor Intel i7 6820HQ
 - Version 0.7
 - Environment VMWare Nested Virtualization

**Additional context**
`EfiDSEFix.exe -e 0x8`

**Comment by xmaple555** [comment] 2023-11-25 17:03
Hi, I also got the problem while build the solution on windows 1909.
![image](https://github.com/HyperDbg/HyperDbg/assets/54590608/3889a53c-d40b-4c52-b3e4-36dbdf6136bf)

I guess the problem is that hyperdbgkd.sys uses some APIs which is not able on windows 1909. 
The current solution is that run hyperdbg on windows 11 or latest windows 10 version.

**Comment by SinaKarvandi** [comment] 2023-11-26 15:04
Hi,
I think the problem is with the changes we made to MTRRs. I experienced the same problem sometimes, but couldn't find a deterministic way of reproducing the error. I try to see whether I can understand the problem from the source code or not, otherwise, we'll probably have to revert to previous MTRR changes. 🤔

**Comment by SinaKarvandi** [comment] 2023-11-26 15:05
> Hi, I got the problem of building the solution on windows 1909. ![image](https://private-user-images.githubusercontent.com/54590608/285605165-3889a53c-d40b-4c52-b3e4-36dbdf6136bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMTEwOTIsIm5iZiI6MTcwMTAxMDc5MiwicGF0aCI6Ii81NDU5MDYwOC8yODU2MDUxNjUtMzg4OWE1M2MtZDQwYi00YzUyLWIzZTQtMzZkYmRmNjEzNmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDE0NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2Y5M2Q3YjU4YTA3ZjdjNDlkZDZkODkxNDYyNWQ1ZTkzZDU3MmFlY2Y1NTk5Njc1YmJiMGFhNDRhZjUzMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-KxY_DN0k4GnqwJlgid6Y3luybLCGcOt9xrPHE0rC4)
> 
> I guess the problem is that hyperdbgkd.sys uses some APIs which is not able on windows 1909. The current solution is that run hyperdbg on windows 11 or latest windows 10 version.

Unfortunately, each update to SDK, WDK, or even visual studio breaks the compilations. I experienced the same issue a lot these years.

**Comment by SinaKarvandi** [comment] 2024-01-12 16:06
Please re-open the issue if the problem still exists.

**Comment by Mattiwatti** [comment] 2024-01-21 23:33
I'm hesitant to *reopen* this as I'm not actually certain this is really the same issue, but I'm definitely experiencing *some* major issue with `load vmm` that very closely matches this description, so I thought it would be worth it to post some notes here at least. I'll ping @Suicolen here as well since I know he also has the same issue with the current release.

What about this issue matches what we are seeing:
1. `load vmm` makes the system unresponsive. But by 'the system' I do mean the *entire system* - i.e., a hard shutdown/poweroff is needed. So that corresponds to @sjzbwdiy's description of test 2 (unresponsive VM), but not test 0 or 1, where only the process stopped responding.

What about this issue does **not** quite match what we are seeing:
1. Me and @Suicolen are both experiencing this on **physical machines** (both 13th gen Intel(R) CPUs, and both using the same Asus Prime Z790-P D4 motherboard - not sure this is related, but it's an interesting coincidence for sure). I don't believe @Suicolen has tested this in a VM, since he was specifically trying to use HyperDbg for hardware debugging/monitoring purposes, so that would sort of defeat the purpose. But, since I noticed @sjzbwdiy used VMware in their tests, I also installed VMware to see if I could reproduce this using nested virtualization instead. The answer is: no, I can't. I have a 0% reproduction rate when using VMware - `load vmm` simply works. When using VMI mode (connected either locally or remotely) on my physical machine, the reproduction rate is 100%, i.e. `load vmm` has never succeeded even once on my machine with any recent release.
2. @sjzbwdiy clearly identified 4f0d0dc3bf3686772a58ebe85221dc3374be8188 as the 'bad' commit when it comes to the issue they're having. I also ran `git bisect` to pinpoint the cause of me and @Suicolen's issue, and arrived at a completely different commit, namely bf6370d5a3d35bb7aeb16ce0d45fd77fda7bcca0. Any build compiled without this commit included (so either simply an older version, but also the current `dev` branch + `git revert bf6370d`) fixes `load vmm` for both of us. So that seems to match @SinaKarvandi's suspicions above re: this being linked to the MTRR map changes.

---

OK, that was a bit longer than I intended, but above is basically the issue we are seeing.

But that brings me to the second reason for posting here (instead of making a new issue, I mean), namely: the good news is that I believe I've managed to fix this (so: fixing a number of issues with the MTRR-related code in `EptGetMemoryType` and `EptBuildMtrrMap`, and not just throwing away the changes). To be clear, I do actually think bf6370d was an improvement for the most part, it just has some unfortunate interactions with existing code in the same file that makes a bunch of different assumptions.

I'm currently preparing a PR with these changes that I should be able to post soon. So, this is all just to say that: I'm working on a fix for an issue that may or may not actually be the same as this one, but which is so similar in the way it manifests that I believe @sjzbwdiy should give it a try. If nothing else, at least then we'll know if we're even talking about the same issue...

**Comment by SinaKarvandi** [comment] 2024-01-22 01:58
> I'm hesitant to _reopen_ this as I'm not actually certain this is really the same issue, but I'm definitely experiencing _some_ major issue with `load vmm` that very closely matches this description, so I thought it would be worth it to post some notes here at least. I'll ping @Suicolen here as well since I know he also has the same issue with the current release.
> 
> What about this issue matches what we are seeing:
> 
> 1. `load vmm` makes the system unresponsive. But by 'the system' I do mean the _entire system_ - i.e., a hard shutdown/poweroff is needed. So that corresponds to @sjzbwdiy's description of test 2 (unresponsive VM), but not test 0 or 1, where only the process stopped responding.
> 
> What about this issue does **not** quite match what we are seeing:
> 
> 1. Me and @Suicolen are both experiencing this on **physical machines** (both 13th gen Intel(R) CPUs, and both using the same Asus Prime Z790-P D4 motherboard - not sure this is related, but it's an interesting coincidence for sure). I don't believe @Suicolen has tested this in a VM, since he was specifically trying to use HyperDbg for hardware debugging/monitoring purposes, so that would sort of defeat the purpose. But, since I noticed @sjzbwdiy used VMware in their tests, I also installed VMware to see if I could reproduce this using nested virtualization instead. The answer is: no, I can't. I have a 0% reproduction rate when using VMware - `load vmm` simply works. When using VMI mode (connected either locally or remotely) on my physical machine, the reproduction rate is 100%, i.e. `load vmm` has never succeeded even once on my machine with any recent release.
> 2. @sjzbwdiy clearly identified [4f0d0dc](https://github.com/HyperDbg/HyperDbg/commit/4f0d0dc3bf3686772a58ebe85221dc3374be8188) as the 'bad' commit when it comes to the issue they're having. I also ran `git bisect` to pinpoint the cause of me and @Suicolen's issue, and arrived at a completely different commit, namely [bf6370d](https://github.com/HyperDbg/HyperDbg/commit/bf6370d5a3d35bb7aeb16ce0d45fd77fda7bcca0). Any build compiled without this commit included (so either simply an older version, but also the current `dev` branch + `git revert bf6370d`) fixes `load vmm` for both of us. So that seems to match @SinaKarvandi's suspicions above re: this being linked to the MTRR map changes.
> 
> OK, that was a bit longer than I intended, but above is basically the issue we are seeing.
> 
> But that brings me to the second reason for posting here (instead of making a new issue, I mean), namely: the good news is that I believe I've managed to fix this (so: fixing a number of issues with the MTRR-related code in `EptGetMemoryType` and `EptBuildMtrrMap`, and not just throwing away the changes). To be clear, I do actually think [bf6370d](https://github.com/HyperDbg/HyperDbg/commit/bf6370d5a3d35bb7aeb16ce0d45fd77fda7bcca0) was an improvement for the most part, it just has some unfortunate interactions with existing code in the same file that makes a bunch of different assumptions.
> 
> I'm currently preparing a PR with these changes that I should be able to post soon. So, this is all just to say that: I'm working on a fix for an issue that may or may not actually be the same as this one, but which is so similar in the way it manifests that I believe @sjzbwdiy should give it a try. If nothing else, at least then we'll know if we're even talking about the same issue...

Thanks for your detailed response. Yes, I believe at some point I talked with @Air14 about this problem but after that, I couldn't reproduce the error. I couldn't reproduce the error on my 12th Gen i5-12400 (both on VMWare Workstation and Physical Machine), but I believe there is a problem with MTRRs. Looking forward to your PR.

**Comment by Mattiwatti** [comment] 2024-01-22 16:06
PR created, see link above.

I'd be curious to hear if it somehow makes a difference w.r.t. your `load vmm` issue, @sjzbwdiy. I'm not hopeful but it would be great if you could give it a try anyway.

**Comment by SinaKarvandi** [comment] 2024-01-24 06:35
It seems that the issue is not completely fixed (at least for 13th-generation processors). For me (12th-generation processor) it's pretty fine on both physical machine as well as VMware nested virtualization but here is a system that is reported to be problematic:

https://t.me/HyperDbg/5484

```
Issue: HyperDbg causes entire system to become unresponsive after running the commands ".connect local"
                                                                                       "load vmm"
                                                                                       
This issue was observed on a Physical System, below are the specifications of said system.


=========================================== msinfo32 System Summary ===========================================
OS Name    Microsoft Windows 11 Home Single Language
Version    10.0.22621 Build 22621
Other OS Description     Not Available
OS Manufacturer    Microsoft Corporation
System Name    MSI
System Manufacturer    Micro-Star International Co., Ltd.
System Model    Katana 15 B13VGK
System Type    x64-based PC
System SKU    1585.1
Processor    13th Gen Intel(R) Core(TM) i9-13900H, 2600 Mhz, 14 Core(s), 20 Logical Processor(s)
BIOS Version/Date    American Megatrends International, LLC. E1585IMS.113, 26/10/2023
SMBIOS Version    3.5
Embedded Controller Version    255.255
BIOS Mode    UEFI
BaseBoard Manufacturer    Micro-Star International Co., Ltd.
BaseBoard Product    MS-1585
BaseBoard Version    REV:1.0
Platform Role    Mobile
Secure Boot State    Off
PCR7 Configuration    Elevation Required to View
Windows Directory    C:\Windows
System Directory    C:\Windows\system32
Boot Device    \Device\HarddiskVolume1
Locale    United States
Hardware Abstraction Layer    Version = "10.0.22621.2506"
User Name    MSI\luist
Time Zone    Malay Peninsula Standard Time
Installed Physical Memory (RAM)    32.0 GB
Total Physical Memory    31.7 GB
Available Physical Memory    27.4 GB
Total Virtual Memory    63.7 GB
Available Virtual Memory    58.2 GB
Page File Space    32.0 GB
Page File    C:\pagefile.sys
Kernel DMA Protection    On
Virtualization-based security    Not enabled
Device Encryption Support    Elevation Required to View
Hyper-V - VM Monitor Mode Extensions    Yes
Hyper-V - Second Level Address Translation Extensions    Yes
Hyper-V - Virtualization Enabled in Firmware    Yes
Hyper-V - Data Execution Protection    Yes


=========================================== GPU ===========================================
Name    NVIDIA GeForce RTX 4070 Laptop GPU
```

**Comment by SinaKarvandi** [comment] 2024-01-24 08:48
@Mattiwatti As it's discussed in the Telegram group. Is it a mistake here? Or you intentionally didn't use the '`j`' variable?

https://t.me/HyperDbg/5499
https://t.me/HyperDbg/5500
https://t.me/HyperDbg/5501
https://t.me/HyperDbg/5502

![image](https://github.com/HyperDbg/HyperDbg/assets/13383992/effe2dcb-acab-47c4-b55e-cdb027cd324e)

**Comment by Mattiwatti** [comment] 2024-01-24 16:50
Hmm, that does certainly does look like a mistake. Albeit one that was already in the commit that originally introduced this loop, so I don't know if it's likely to be responsible for any **new** issues.

I will create a fix commit for this ASAP, but unfortunately I'll be away today and most of tomorrow so there will be some delay. Otherwise, you could also fix it yourself if needed; the loop immediately below this one does use the correct indexing that incorporates `j`, so this should be straightforward.

(Sidenote: I've tried to join the Telegram HyperDbg group before, but failed to do so because the desktop version of Telegram requires me to log in with a mobile Telegram account, and the mobile version of Telegram fails to send me an activation message, and also fails when trying to call the same number for activation instead. So as is, it seems I'm not able to join Telegram at all.)

**Comment by SinaKarvandi** [comment] 2024-01-25 05:20
> Hmm, that does certainly look like a mistake. Albeit one that was already in the commit that originally introduced this loop, so I don't know if it's likely to be responsible for any **new** issues.
> 
> I will create a fix commit for this ASAP, but unfortunately I'll be away today and most of tomorrow so there will be some delay. Otherwise, you could also fix it yourself if needed; the loop immediately below this one does use the correct indexing that incorporates `j`, so this should be straightforward.
> 
> (Sidenote: I've tried to join the Telegram HyperDbg group before, but failed to do so because the desktop version of Telegram requires me to log in with a mobile Telegram account, and the mobile version of Telegram fails to send me an activation message, and also fails when trying to call the same number for activation instead. So as is, it seems I'm not able to join Telegram at all.)

Thanks for your response. Well, I would rather delegate the task of resolving the issue to you, especially considering that the issue mostly occurs on 13th-generation Intel processors, so you can confirm whether it's problematic on your system or not. Once the patch is applied, I'll ask community members to test and verify whether the patch will fix the problem of those who report having problems with v0.7.2 or not and will let you know.

**Comment by SinaKarvandi** [comment] 2024-01-27 08:19
I made a simple change to the 'Dev' to fix the discussed issue.

**Comment by SinaKarvandi** [comment] 2024-01-27 08:20
https://github.com/HyperDbg/HyperDbg/commit/ed5ab28aff74c20f095ce59eb6534a8647d69e07

If you've still encountered any problem after this patch (especially on 13th gen Intel processors) please let me know.

**Comment by SinaKarvandi** [comment] 2024-02-02 03:55
Since this problem is solved, I'll close this issue. Thank you all for helping solve this issue.

**Closed by SinaKarvandi** 2024-02-02 03:55 UTC
Labels: bug
