### ISSUE TITLE
There is a bug in the EPT HOOK code. (Use Zydis instead of current disassembler in kernel)

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#44] opened 2021-07-28 08:51 UTC
EptHookInstructionMemory

`

    for (SizeOfHookedInstructions = 0;
         SizeOfHookedInstructions < 18;
         SizeOfHookedInstructions += ldisasm(((UINT64)TargetFunctionInSafeMemory + SizeOfHookedInstructions), TRUE))
    {
        //
        // Get the full size of instructions necessary to copy
        //
    }
`

The ldisasm function has a problem with the code length in the calculation of ObReferenceObjectByHandle, and the calculation result is smaller than the expected result

**Comment by wuhao13** [comment] 2021-07-28 13:55
Sorry, I found that the problem is not that simple, only the detection of instruction length deviation in ObReferenceObjectByHandle, and there seems to be no such problem in other places, this is a strange situation.

**Comment by SinaKarvandi** [comment] 2021-07-28 14:05
okay, please provide updates if you understand the problem. I think the problem might be because of our Length Dissembler Engine.

**Comment by wuhao13** [comment] 2021-07-28 14:34
Yes, when I tried to replace it with the LDE of gbgv, the problem seemed to be resolved. Now I believe that there is a small BUG in Length Dissembler Engine

**Comment by SinaKarvandi** [comment] 2021-07-28 14:45
Yep, but that LDE has its own problems. I think I have to change our LDE to Zydis's LDE in the future.

**Comment by wuhao13** [comment] 2021-07-28 14:48
I look forward to your updates, let us work together to make this code more stable!

**Comment by SinaKarvandi** [comment] 2021-07-28 14:50
Thank you. 
We're currently working on our academic paper for HyperDbg. But soon, we'll return to fix all of these problems.

**Comment by wuhao13** [comment] 2021-07-28 14:55
Good luck！bye！

**Comment by SinaKarvandi** [comment] 2022-05-18 09:58
The progress about fixing this specific error? or an overall progress report?

**Comment by SinaKarvandi** [comment] 2022-05-19 11:18
I'll try to fix it soon.

**Comment by L1B0** [comment] 2022-05-25 07:59
Hi, I have a question about these codes in EptHookInstructionMemory function.

Is these codes mean calculate the instruction length of target hook function until SizeOfHookedInstructions > 19?
And Is ldisasm function to seem the param1 as a start address to get the instruction length?
```
for (SizeOfHookedInstructions = 0;
         SizeOfHookedInstructions < 19;
         SizeOfHookedInstructions += ldisasm(((UINT64)TargetFunctionInSafeMemory + SizeOfHookedInstructions), TRUE))
    {
        //
        // Get the full size of instructions necessary to copy
        //
    }
```

Because I try to hook ZwUnloadDriver by using Hypervisor From Scratch code project, and the SizeOfHookedInstructions is 15, which is same as hooking ExAllocatePoolWithTag,  as well as it should be 19, and so I got BSOD.

```
.text:0000000140415360                                     ; Exported entry 3039. ZwUnloadDriver
.text:0000000140415360
.text:0000000140415360                                                     public ZwUnloadDriver
.text:0000000140415360                                     ZwUnloadDriver:                         ; CODE XREF: DifZwUnloadDriverWrapper+B6↓p
.text:0000000140415360                                                                             ; EtwpUpdateFileInfoDriverState+1D4BC7↓p ...
.text:0000000140415360 48 8B C4                                            mov     rax, rsp
.text:0000000140415363 FA                                                  cli
.text:0000000140415364 48 83 EC 10                                         sub     rsp, 10h
.text:0000000140415368 50                                                  push    rax
.text:0000000140415369 9C                                                  pushfq
.text:000000014041536A 6A 10                                               push    10h
.text:000000014041536C 48 8D 05 6D 4A 00 00                                lea     rax, KiServiceLinkage
.text:0000000140415373 50                                                  push    rax
.text:0000000140415374 B8 D1 01 00 00                                      mov     eax, 1D1h
.text:0000000140415379 E9 C2 22 01 00                                      jmp     KiServiceInternal
.text:000000014041537E                                     ; ---------------------------------------------------------------------------
.text:000000014041537E C3                                                  retn
```

By the way, why you set 19 as the max number of SizeOfHookedInstructions in Hyperdbg? I have tried to just get the first instruction length of target function as the value of SizeOfHookedInstructions , but I got BSOD. And I use bddisasm as  disassemble engine, it is worked correctly to calculate instruction length.

**Comment by L1B0** [comment] 2022-05-26 09:33
I think I have known the reason of why I got BSOD when trying to hook ZwUnhookDriver.

Because the instruction of 000000014041536C has a related offset to KiServiceLinkage, so we can't patch the address more than 000000014041536C.
But the length of above is 000000014041536C just 12, which is less than the absoluted jmp instruction length 13.

And I'm trying to find the shorter length of trampoline code.

**Comment by L1B0** [comment] 2022-05-26 14:18
I have found a trampoline code, which has length 12.

```
48 b8 00 00 b3 64 00 f8 ff ff     mov rax, 0xfffff80064b30000
ff e0                             jmp rax
```

**Comment by SinaKarvandi** [comment] 2022-05-28 19:38
Hi,
Thanks for putting your time into investigating this problem and sorry for the late response.

> By the way, why you set 19 as the max number of SizeOfHookedInstructions in Hyperdbg? Is it related to the length of absolute jmp instruction?

Yes, it's related to absolute jmp instruction.

I didn't get the point. Did you conclude that the length disassembler engine has a problem? Am I right?

**Comment by L1B0** [comment] 2022-05-29 02:27
Honestly I didn't test in the Hyperdbg, but instead Hypervisor From Scratch, whose  length disassembler engine maybe has a problem. Because I try to hook ZwUnloadDriver but the SizeOfHookedInstructions is wrong. 

And the point I really want to say is about the design of trampoline code.

I think the length 19 of trampoline code in HyperDbg is a little bit long, maybe you can test to hook ZwUnloadDriver in hyperdbg, I'm interested in the result of SizeOfHookedInstructions and whether there have BSOD.

Because as above I said, at the offset **0xc** of function ZwUnloadDriver, the instruction is `lea     rax, KiServiceLinkage`, which calculate the really address of KiServiceLinkage by adding current instruction address and the offset. 

And in hyperdbg the length of SizeOfHookedInstructions should greater than **19**, which will make this instruction copid in trampoline code, and the really address of KiServiceLinkage will be wrong because the current instruction address is wrong.

That's why I design a length 12 trampoline code as above.

Thanks!

**Comment by L1B0** [comment] 2022-05-29 06:20
How much is the length of the above instruction?

**Comment by L1B0** [comment] 2022-05-29 06:51
That's a good way that I haven't known before! It won't modify any registers or stack.

But its length maybe too long for some functions, such as ZwUnhookDriver.

**Comment by L1B0** [comment] 2022-05-29 07:31
I create a example opcode of that, is that correct?

```
.text:00000001400052A7 FF 25 02 00 00 00                       jmp     cs:qword_1400052AF
.text:00000001400052A7                         sub_1400052A7   endp
.text:00000001400052A7
.text:00000001400052A7                         ; ---------------------------------------------------------------------------
.text:00000001400052AD 00                      unk_1400052AD   db    0                 ; CODE XREF: ZwUnloadDriverHook+65↑j
.text:00000001400052AE 00                                      db    0
.text:00000001400052AF 00 00 EA 11 08 BF FF FF qword_1400052AF dq 0FFFFBF0811EA0000h 
```

**Comment by SinaKarvandi** [comment] 2022-05-29 07:38
> And in hyperdbg the length of SizeOfHookedInstructions should greater than **19**, which will make this instruction copid in trampoline code, and the really address of KiServiceLinkage will be wrong because the current instruction address is wrong.

The Length Disassembler Engine in HyperDbg is different, it's not the same as hypervisor from scratch and also the trampoline is different. If you want to use HyperDbg, you should use !epthook2 for this purpose:
[!epthook2](https://docs.hyperdbg.org/commands/extension-commands/epthook2)

**Comment by L1B0** [comment] 2022-05-29 07:45
Yeah, I check the trampoline code in Hyperdbg, it's on the function EptHookWriteAbsoluteJump. But this trampoline code is still has problems when try to hook ZwUnhookDriver I think, because its length is 19.
```

/**
 * @brief Write an absolute x64 jump to an arbitrary address to a buffer
 * 
 * @param TargetBuffer 
 * @param TargetAddress 
 * @return VOID 
 */
VOID
EptHookWriteAbsoluteJump(PCHAR TargetBuffer, SIZE_T TargetAddress)
{
    //
    // call $ + 5 ; A 64-bit call instruction is still 5 bytes wide!
    //
    TargetBuffer[0] = 0xe8;
    TargetBuffer[1] = 0x00;
    TargetBuffer[2] = 0x00;
    TargetBuffer[3] = 0x00;
    TargetBuffer[4] = 0x00;

    //
    // push Lower 4-byte TargetAddress
    //
    TargetBuffer[5] = 0x68;

    //
    // Lower 4-byte TargetAddress
    //
    *((PUINT32)&TargetBuffer[6]) = (UINT32)TargetAddress;

    //
    // mov [rsp+4],High 4-byte TargetAddress
    //
    TargetBuffer[10] = 0xC7;
    TargetBuffer[11] = 0x44;
    TargetBuffer[12] = 0x24;
    TargetBuffer[13] = 0x04;

    //
    // High 4-byte TargetAddress
    //
    *((PUINT32)&TargetBuffer[14]) = (UINT32)(TargetAddress >> 32);

    //
    // ret
    //
    TargetBuffer[18] = 0xC3;
}
```

**Comment by SinaKarvandi** [comment] 2022-05-29 07:48
19 bytes is because we want to pass the current RIP to the hooking function.
The opcodes get the current RIP, what else we can do? In HyperDbg users might set hundreds of hooks, we need to trace the exact location.

**Comment by SinaKarvandi** [comment] 2022-05-29 07:48
I still didn't get the problem. What's wrong with 19 bytes?

**Comment by L1B0** [comment] 2022-05-29 08:05
Ok, let me show you a example that hooking the function ZwUnhookDriver by using your trampoline code.

Firstly, We will replace the first 19 bytes spaces of ZwUnhookDriver function that are the following code to set a absolute jmp:
```
.text:0000000140415360                                     ; Exported entry 3039. ZwUnloadDriver
.text:0000000140415360
.text:0000000140415360                                                     public ZwUnloadDriver
.text:0000000140415360                                     ZwUnloadDriver:                         ; CODE XREF: DifZwUnloadDriverWrapper+B6↓p
.text:0000000140415360                                                                             ; EtwpUpdateFileInfoDriverState+1D4BC7↓p ...
.text:0000000140415360 48 8B C4                                            mov     rax, rsp
.text:0000000140415363 FA                                                  cli
.text:0000000140415364 48 83 EC 10                                         sub     rsp, 10h
.text:0000000140415368 50                                                  push    rax
.text:0000000140415369 9C                                                  pushfq
.text:000000014041536A 6A 10                                               push    10h
.text:000000014041536C 48 8D 05 6D 4A 00 00                                lea     rax, KiServiceLinkage
```

Also these replaced original code will be copied to the trampoline page, and on the trampoline page, it will jmp to ZwUnloadDriver+19 after the orignal code.

And the problem is, on the trampoline page, it executes the original code of ZwUnloadDriver firstly, and the instruction is "lea     rax, KiServiceLinkage" at last, which uses a relative offset to locate the address of KiServiceLinkage. 

But on the trampoline page, the instruction address that is executing is different to original function address, so the result of caculating address of KiServiceLinkage is wrong! 

I don't know  whether I explain clearly this time hhh.

**Comment by SinaKarvandi** [comment] 2022-05-29 08:11
I get it. But this is the classic problem with detours-style hooks. I don't think there is any solution to this problem (if you know, please let me know).

I also told about this problem in the documentation : 
![image](https://user-images.githubusercontent.com/13383992/170858661-3c45cf1e-1be7-4e44-a13b-c039d6905ff3.png)

The solution to this problem is to use the !epthook instead of the !epthook2 in HyperDbg. 
https://docs.hyperdbg.org/commands/extension-commands/epthook

It uses hidden 1 one-byte breakpoint which is intercepted by hypervisor.

**Comment by L1B0** [comment] 2022-05-29 08:26
Ok, I know it:)

**Comment by SinaKarvandi** [comment] 2023-06-06 10:39
The length disassembler engine is now updated to Zydis. (https://github.com/HyperDbg/HyperDbg/pull/234) 
It's merged in the 'Dev' branch, not the 'Master'.

I think the problem should be solved now. Please re-open the issue if it was still problematic.

**Closed by SinaKarvandi** 2023-06-06 10:39 UTC
Labels: enhancement
