### ISSUE TITLE
compiling last vetsion

### ISSUE THREAD

**Issue by Alexi0n** [HyperDbg/HyperDbg#215] opened 2023-02-02 21:18 UTC
my configuration VS 2022+SDK2022+WDK2022
![Снимок экрана 2023-02-03 001538](https://user-images.githubusercontent.com/121357876/216451757-d25f91ad-3d74-44dd-8618-09e5055f2952.jpg)

**Comment by SinaKarvandi** [comment] 2023-02-04 11:19
Hi,
Thanks for creating this issue.
We completely refactored the HyperDbg and now the refactored version is available on the 'dev' branch which works well with the new SDK. However, the refactored version is not yet tested and I expect it to have errors so it's not recommended to use the 'dev' version. For now, for compiling the 'master' branch you should use the previous SDK (and probably an older version of VS), soon we will test and merge the 'dev' branch to the 'master' branch and this problem will be solved.

**Comment by SinaKarvandi** [comment] 2023-02-18 02:58
Hi,
Yes, it works on Win11 and also you can compile the 'Dev' branch in Win 11. I didn't test the Dev branch, but it should be fine (probably some minor issues).

**Comment by myasn1k** [comment] 2023-02-18 15:07
Thanks a lot, it works!
There were like 70 errors, I had to add an `#include <string>` in `PDB.h` and everything is fixed now.
The only thing i don't understand now is why it hangs here:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti riservati.

Installa la versione più recente di PowerShell per nuove funzionalità e miglioramenti. https://aka.ms/PSWindows

PS C:\Users\USER> cd C:\Users\USER\source\repos\HyperDbg\hyperdbg\build\bin\release
PS C:\Users\USER\source\repos\HyperDbg\hyperdbg\build\bin\release> .\hyperdbg-cli.exe
HyperDbg Debugger [version: v0.2.0, build: 20230218]
Please visit https://docs.hyperdbg.org for more information...
HyperDbg is released under the GNU Public License v3 (GPLv3).

HyperDbg> .connect local
local debugging (vmi-mode)

HyperDbg> load vmm
loading the vmm driver
current processor vendor is : GenuineIntel
virtualization technology is vt-x
vmx operation is supported by your processor
vmm module is running...
interpreting symbols and creating symbol maps

HyperDbg> .start path c:\Windows\system32\notepad.exe
```

**Comment by SinaKarvandi** [comment] 2023-02-19 06:31
Yes, I test it and there is an error. Probably, caused by recent refactoring codes. I'll fix it.

**Comment by myasn1k** [comment] 2023-03-24 15:50
Hi, sorry bothering you again @SinaKarvandi.
I still can't run notepad under hyperdbg in Windows 11. 
I tried both dev and master branches.
Here are logs of the terminal:
- Main branch: https://pastebin.com/aL1ayS17
  - And then BSOD
- Dev branch: https://pastebin.com/ksj8zUUy
  - And then BSOD

**Comment by SinaKarvandi** [comment] 2023-04-07 04:57
hi @myasn1k ,
Sorry for the delayed response.
Did you use the ".start" command in debugger mode?

I fixed an issue in the "Dev" branch. That might fix the problem.

**Comment by myasn1k** [comment] 2023-04-07 08:26
Thanks for the answer @SinaKarvandi !
Yes in both I did `.start path c:\Windows\system32\notepad.exe`
I'll try asap to rebuild the Dev branch and test it out! 
Thanks again, I'll keep you updated.

**Comment by myasn1k** [comment] 2023-04-27 10:43
@SinaKarvandi sorry for the delayed response
Unfortunately also the new Dev branch gives me problems
When I start notepad the entrypoint break is reached but when I try doing g or t the machine freezes.
Do you have some hints or suggestions? 

Thanks a lot for your help!

**Comment by SinaKarvandi** [comment] 2023-04-27 11:02
> @SinaKarvandi sorry for the delayed response Unfortunately also the new Dev branch gives me problems When I start notepad the entrypoint break is reached but when I try doing g or t the machine freezes. Do you have some hints or suggestions?
> 
> Thanks a lot for your help!

Hi, 
Oops, I just understand the problem. You're using user-mode debugger which is not yet in a working state. I thought you were using the debugger in the Debugger Mode (kernel debugger). So, that's the problem. I might decide to discontinue the u64HyperDbg and u86HyperDbg because it has some fundamental problems that are still unsolvable. But the kHyperDbg is pretty okay and working. 

Sorry for the inconvenience, I just forgot to completely disable the user-debugger.
آه

**Closed** 2023-06-02 05:13 UTC
